<a href="https://colab.research.google.com/github/sumits-14/Data_Science/blob/main/FIFA_Pandas_35_Practice_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FIFA Data Science Practice – Pandas Only**

**Instructions:** Solve every question using the **Pandas** library only. Do not create plots. Each question is followed by an empty code cell for your solution.

## **1. Load the `fifa_eda.csv` dataset into a Pandas DataFrame.**

In [ ]:
import pandas as pd

In [ ]:
ds = pd.read_csv('fifa_eda.csv')
ds

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

## **2. Display the first 5 records of the dataset.**

In [ ]:
ds.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

## **3. Check the shape of the dataset, column names, and data types of all columns.**

In [ ]:
ds.shape

(18207, 18)

## **4. Generate the statistical summary of the dataset using Pandas.**

In [ ]:
ds.describe()

,ID,Age,Overall,Potential,Value,Wage,International Reputation,Skill Moves,Joined,Height,Weight,Release Clause
count,18207.000000,18207.000000,18207.000000,18207.000000,17955.000000,18207.000000,18159.000000,18159.000000,18207.000000,18207.000000,18207.000000,18207.000000
mean,214298.338606,25.122206,66.238699,71.307299,2444.530214,9.731312,1.113222,2.361308,2016.420607,5.946771,165.979129,4585.060971
std,29965.244204,4.669943,6.908930,6.136496,5626.715434,21.999290,0.394031,0.756164,2.018194,0.220514,15.572775,10630.414430
min,16.000000,16.000000,46.000000,48.000000,10.000000,0.000000,1.000000,1.000000,1991.000000,5.083333,110.000000,13.000000
25%,200315.500000,21.000000,62.000000,67.000000,325.000000,1.000000,1.000000,2.000000,2016.000000,5.750000,154.000000,570.000000
50%,221759.000000,25.000000,66.000000,71.000000,700.000000,3.000000,1.000000,2.000000,2017.000000,5.916667,165.000000,1300.000000
75%,236529.500000,28.000000,71.000000,75.000000,2100.000000,9.000000,1.000000,3.000000,2018.000000,6.083333,176.000000,4585.060806
max,246620.000000,45.000000,94.000000,95.000000,118500.000000,565.000000,5.000000,5.000000,2018.000000,6.750000,243.000000,228100.000000

In [ ]:
ds.describe(include='all')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
count,18207.000000,18207,18207.000000,18207,18207.000000,18207.000000,17966,17955.000000,18207.000000,18207,18159.000000,18159.000000,18207,18207.000000,17918,18207.000000,18207.000000,18207.000000
unique,NaN,17194,NaN,164,NaN,NaN,651,NaN,NaN,2,NaN,NaN,27,NaN,35,NaN,NaN,NaN
top,NaN,J. Rodríguez,NaN,England,NaN,NaN,RC Celta,NaN,NaN,Right,NaN,NaN,ST,NaN,2019-01-01,NaN,NaN,NaN
freq,NaN,11,NaN,1662,NaN,NaN,33,NaN,NaN,13996,NaN,NaN,2154,NaN,4870,NaN,NaN,NaN
mean,214298.338606,NaN,25.122206,NaN,66.238699,71.307299,NaN,2444.530214,9.731312,NaN,1.113222,2.361308,NaN,2016.420607,NaN,5.946771,165.979129,4585.060971
std,29965.244204,NaN,4.669943,NaN,6.908930,6.136496,NaN,5626.715434,21.999290,NaN,0.394031,0.756164,NaN,2.018194,NaN,0.220514,15.572775,10630.414430
min,16.000000,NaN,16.000000,NaN,46.000000,48.000000,NaN,10.000000,0.000000,NaN,1.000000,1.000000,NaN,1991.000000,NaN,5.083333,110.000000,13.000000
25%,200315.500000,NaN,21.000000,NaN,62.000000,67.000000,NaN,325.000000,1.000000,NaN,1.000000,2.000000,NaN,2016.000000,NaN,5.750000,154.000000,570.000000
50%,221759.000000,NaN,25.000000,NaN,66.000000,71.000000,NaN,700.000000,3.000000,NaN,1.000000,2.000000,NaN,2017.000000,NaN,5.916667,165.000000,1300.000000
75%,236529.500000,NaN,28.000000,NaN,71.000000,75.000000,NaN,2100.000000,9.000000,NaN,1.000000,3.000000,NaN,2018.000000,NaN,6.083333,176.000000,4585.060806
max,246620.000000,NaN,45.000000,NaN,94.000000,95.000000,NaN,118500.000000,565.000000,NaN,5.000000,5.000000,NaN,2018.000000,NaN,6.750000,243.000000,228100.000000

## **5. Check the number of missing values in each column and sort the result from highest to lowest.**

In [ ]:
ns = ds.isnull()
ns

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18203,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18204,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18205,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18206,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
ss = ns.sum()
ss

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [ ]:
missing = ss.sort_values(ascending=False)
missing

Contract Valid Until        289
Value                       252
Club                        241
International Reputation     48
Skill Moves                  48
ID                            0
Name                          0
Potential                     0
Age                           0
Nationality                   0
Preferred Foot                0
Wage                          0
Overall                       0
Position                      0
Joined                        0
Height                        0
Weight                        0
Release Clause                0
dtype: int64

## **6. Check whether there are any duplicate rows and whether the `ID` column contains duplicate player IDs.**

In [ ]:
print(ds.duplicated())
print(ds.duplicated().sum())

0        False
1        False
2        False
3        False
4        False
         ...
18202    False
18203    False
18204    False
18205    False
18206    False
Length: 18207, dtype: bool
0

In [ ]:
ds['ID'].duplicated().sum()

np.int64(0)

## **7. Find the total number of players from each `Nationality` and display the top 10 nationalities with the most players.**

In [ ]:
ds['Nationality'].value_counts()

Nationality
England        1662
Germany        1198
Spain          1072
Argentina       937
France          914
               ...
Malta             1
Belize            1
South Sudan       1
Indonesia         1
Botswana          1
Name: count, Length: 164, dtype: int64

In [ ]:
ds['Nationality'].value_counts().head(10)

Nationality
England        1662
Germany        1198
Spain          1072
Argentina       937
France          914
Brazil          827
Italy           702
Colombia        618
Japan           478
Netherlands     453
Name: count, dtype: int64

In [ ]:
# In the form of dataframe
ds['Nationality'].value_counts().head(10).reset_index()

   Nationality  count
0      England   1662
1      Germany   1198
2        Spain   1072
3    Argentina    937
4       France    914
5       Brazil    827
6        Italy    702
7     Colombia    618
8        Japan    478
9  Netherlands    453

## **8. Find the total number of players in each `Club` and display the top 10 clubs with the most players.**

In [ ]:
ds['Club'].value_counts()

Club
RC Celta               33
Everton                33
Valencia CF            33
Borussia Dortmund      33
TSG 1899 Hoffenheim    33
                       ..
Botafogo               20
Vitória                20
Sligo Rovers           19
Limerick FC            19
Derry City             18
Name: count, Length: 651, dtype: int64

In [ ]:
ds['Club'].value_counts().head(10)

Club
RC Celta                   33
Everton                    33
Valencia CF                33
Borussia Dortmund          33
TSG 1899 Hoffenheim        33
Wolverhampton Wanderers    33
AS Monaco                  33
Real Madrid                33
Atlético Madrid            33
Manchester United          33
Name: count, dtype: int64

## **9. Calculate the average `Overall` rating for each `Position` and sort the positions from highest to lowest average rating.**

In [ ]:
op = ds.groupby('Position')['Overall'].mean()
op

Position
CAM    66.905109
CB     65.024733
CDM    66.313291
CF     65.824324
CM     63.731183
GK     64.593981
LAM    71.857143
LB     65.713557
LCB    69.240741
LCM    69.270886
LDM    69.032922
LF     73.866667
LM     66.692237
LS     70.062802
LW     66.616798
LWB    66.512821
RAM    72.285714
RB     66.058869
RCB    69.283988
RCM    69.076726
RDM    69.754032
RF     73.250000
RM     66.477374
RS     69.522167
RW     66.929730
RWB    64.655172
ST     65.526927
Name: Overall, dtype: float64

In [ ]:
op.sort_values(ascending=False)

Position
LF     73.866667
RF     73.250000
RAM    72.285714
LAM    71.857143
LS     70.062802
RDM    69.754032
RS     69.522167
RCB    69.283988
LCM    69.270886
LCB    69.240741
RCM    69.076726
LDM    69.032922
RW     66.929730
CAM    66.905109
LM     66.692237
LW     66.616798
LWB    66.512821
RM     66.477374
CDM    66.313291
RB     66.058869
CF     65.824324
LB     65.713557
ST     65.526927
CB     65.024733
RWB    64.655172
GK     64.593981
CM     63.731183
Name: Overall, dtype: float64

## **10. Calculate the average `Potential` rating for each `Position` and identify the top 5 positions by average potential.**

In [ ]:
ds.groupby('Position')['Potential'].mean().sort_values(ascending=False).head(5)

Position
LF     76.600000
RF     75.437500
RW     73.329730
LW     73.123360
RAM    72.857143
Name: Potential, dtype: float64

## **11. Calculate the average `Wage` for each `Position` and display the top 10 highest-paying positions.**

In [ ]:
ds.groupby('Position')['Wage'].mean().sort_values(ascending=False).head(10)

Position
RF     52.687500
LF     44.666667
LAM    26.142857
RAM    19.095238
LS     15.260870
RW     14.432432
RCM    14.404092
RS     14.379310
LCM    14.131646
LW     13.068241
Name: Wage, dtype: float64

## **12. Calculate the average `Value` of players for each `Position` and sort the result from highest to lowest.**

In [ ]:
ds.groupby('Position')['Value'].mean().sort_values(ascending=False)

Position
LF     17153.333333
RF     12562.187500
LAM     6065.476190
RAM     5329.761905
LS      4902.208738
LCM     4330.771208
RCM     4166.098191
RS      4100.746269
RW      3680.561644
LW      3516.243316
CF      3271.621622
LDM     3232.217573
RDM     3160.955285
CAM     3112.045455
RCB     3092.776074
LCB     3072.023622
LM      2821.293738
RM      2760.884201
ST      2350.640845
LWB     2303.333333
CDM     2100.555556
CM      1990.733479
RWB     1945.402299
RB      1718.659306
LB      1692.740385
GK      1614.517345
CB      1610.045688
Name: Value, dtype: float64

## **13. Find the clubs having at least 20 players in the dataset, then identify the top 10 clubs with the highest average `Overall` rating.**

In [ ]:
ds.head(2)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [ ]:
a = ds.groupby('Club').agg(
    players = ('Overall', 'count'),
    avg = ('Overall', 'mean')
)
a

                       players        avg
Club
 SSV Jahn Regensburg        29  65.586207
1. FC Heidenheim 1846       28  65.750000
1. FC Kaiserslautern        26  63.384615
1. FC Köln                  28  70.785714
1. FC Magdeburg             26  65.615385
...                        ...        ...
Zagłębie Sosnowiec          25  60.760000
Çaykur Rizespor             30  66.900000
Örebro SK                   27  60.481481
Östersunds FK               22  63.545455
Śląsk Wrocław               25  62.200000

[651 rows x 2 columns]

In [ ]:
f = (a[a['players'] >= 20]).sort_values('avg',ascending=False).head(10)
f

                     players        avg
Club
Juventus                  25  82.280000
Napoli                    25  80.000000
Inter                     24  79.750000
Real Madrid               33  78.242424
Milan                     27  78.074074
FC Barcelona              33  78.030303
Paris Saint-Germain       30  77.433333
Roma                      26  77.423077
Manchester United         33  77.242424
FC Bayern München         29  77.000000

## **14. Find the nationalities having at least 10 players, then identify the top 10 nationalities with the highest average `Potential`.**

In [ ]:
ds.head(2)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [ ]:
nc = ds['Nationality'].value_counts()
nc10 = nc[nc >= 10]
avg = (ds[ds['Nationality'].isin(nc10.index)]).groupby("Nationality")['Potential'].mean().sort_values(ascending=False).head(10)
avg

Nationality
Croatia     77.691358
Russia      77.072727
Nigeria     76.593750
Ukraine     76.400000
Portugal    76.306202
Slovakia    76.258065
France      76.175197
Spain       76.165478
Belgium     76.018987
Serbia      76.000000
Name: Potential, dtype: float64

## **15. Compare Left-footed and Right-footed players using the average `Overall`, `Potential`, `Value`, and `Wage`.**

In [ ]:
ds.groupby("Preferred Foot")[['Overall', 'Potential', 'Value', 'Wage']].mean()

                  Overall  Potential        Value       Wage
Preferred Foot
Left            71.944099  74.698519  4845.312955  18.451983
Right           72.014176  74.693220  4724.519366  18.131433

## **16. Display the top 10 players with the highest `Overall` rating along with their `Name`, `Age`, `Nationality`, `Club`, `Position`, and `Overall`.**

In [ ]:
ds.sort_values('Overall', ascending=False)[['Name', 'Age', 'Nationality', 'Club', 'Position', 'Overall']].head(10)

                 Name  Age Nationality                 Club Position  Overall
0            L. Messi   31   Argentina         FC Barcelona       RF       94
1   Cristiano Ronaldo   33    Portugal             Juventus       ST       94
2           Neymar Jr   26      Brazil  Paris Saint-Germain       LW       92
3              De Gea   27       Spain    Manchester United       GK       91
7           L. Suárez   31     Uruguay         FC Barcelona       RS       91
8        Sergio Ramos   32       Spain          Real Madrid      RCB       91
5           E. Hazard   27     Belgium              Chelsea       LF       91
4        K. De Bruyne   27     Belgium      Manchester City      RCM       91
6           L. Modrić   32     Croatia          Real Madrid      RCM       91
11           T. Kroos   28     Germany          Real Madrid      LCM       90

## **17. Display the top 10 players with the highest `Potential` along with their `Name`, `Age`, `Club`, `Overall`, and `Potential`.**

In [ ]:
ds.sort_values('Potential', ascending=False)[['Name', 'Age', 'Club', 'Overall', 'Potential']].head(10)

                   Name  Age                 Club  Overall  Potential
25            K. Mbappé   19  Paris Saint-Germain       88         95
1     Cristiano Ronaldo   33             Juventus       94         94
0              L. Messi   31         FC Barcelona       94         94
15            P. Dybala   24             Juventus       89         94
3                De Gea   27    Manchester United       91         93
229       G. Donnarumma   19                Milan       82         93
2             Neymar Jr   26  Paris Saint-Germain       92         93
9              J. Oblak   25      Atlético Madrid       90         93
4          K. De Bruyne   27      Manchester City       91         92
1143    Vinícius Júnior   17          Real Madrid       77         92

## **18. Create a new column called `Potential_Gap` as `Potential - Overall` and find the 10 players with the largest potential improvement gap.**

In [ ]:
ds['Potential_Gap'] = ds['Potential'] - ds['Overall']
t10 = ds.sort_values('Potential_Gap', ascending=False)[['Name', 'Overall', 'Potential', 'Potential_Gap']].head(10)
t10

              Name  Overall  Potential  Potential_Gap
7414     S. Tonali       68         89             21
7758   P. Pellegri       67         88             21
6102    Riqui Puig       69         89             20
7952    A. Bastoni       67         87             20
8191      A. Gomes       67         87             20
7217  Sergio Gómez       68         87             19
8145     A. Gouiri       67         86             19
6032        J. Arp       69         88             19
5007    Kangin Lee       70         88             18
7405     M. Barrow       68         85             17

## **19. Create age groups using Pandas `cut()` such as `16-20`, `21-25`, `26-30`, `31-35`, and `36+`, then calculate the average `Overall` and `Potential` for each age group.**

In [ ]:
bins = [15, 20, 25, 30, 35, float('inf')]
label = ['16-20', '21-25', '26-30', '31-35', '36+']
ds['Age_Group'] = pd.cut(
    ds['Age'],
    bins=bins,
    labels=label
)
ds.groupby("Age_Group", observed=True)[['Overall', 'Potential']].mean()

             Overall  Potential
Age_Group
16-20      70.726368  82.271144
21-25      71.673301  77.296500
26-30      72.217013  72.813588
31-35      72.434528  72.434528
36+        71.994118  71.994118

## **20. Calculate the average `Value` and average `Wage` for each player `Age`, and sort the result by age.**

In [ ]:
ds.groupby('Age')[['Value', 'Wage']].mean().sort_index()

           Value       Wage
Age
17   4320.000000  15.500000
18   4119.047619  11.627907
19   5690.291262  11.663462
20   4586.673554  14.506122
21   5059.024390  15.870732
22   5757.683742  18.749455
23   5364.632107  16.548173
24   5428.586801  16.973126
25   5535.096154  18.366848
26   5417.288862  19.796651
27   5471.164575  20.344828
28   4772.424893  20.030641
29   4635.296474  19.993721
30   4248.346457  18.060372
31   4764.487448  22.109053
32   3894.024725  20.294118
33   2911.863118  18.607407
34   1732.934028  13.955326
35   1353.954545  10.605263
36    997.394366   9.211268
37    967.745098  10.211538
38    348.684211   7.750000
39    352.352941   5.823529
40   1238.750000  18.500000
41     60.000000   2.000000
45    160.000000   8.000000

## **21. Find the top 10 players aged 21 or below with the highest `Potential`.**

In [ ]:
ds[ds['Age'] <= 21].sort_values('Potential', ascending=False).head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
25,231747,K. Mbappé,19,France,88,95,Paris Saint-Germain,81000.0,100.0,Right,3.0,5.0,RM,2018,2022-01-01,5.833333,161.0,166100.0
229,230621,G. Donnarumma,19,Italy,82,93,Milan,29000.0,23.0,Right,3.0,1.0,GK,2015,2021-01-01,6.416667,198.0,55100.0
1143,238794,Vinícius Júnior,17,Brazil,77,92,Real Madrid,17500.0,66.0,Right,1.0,5.0,LW,2018,2025-01-01,5.750000,161.0,46800.0
155,231443,O. Dembélé,21,France,83,92,FC Barcelona,40000.0,155.0,Left,3.0,4.0,RW,2017,2022-01-01,5.833333,148.0,90000.0
156,230666,Gabriel Jesus,21,Brazil,83,92,Manchester City,41000.0,130.0,Right,2.0,4.0,ST,2016,2023-01-01,5.750000,161.0,84100.0
226,235243,M. de Ligt,18,Netherlands,82,91,Ajax,27000.0,11.0,Right,2.0,2.0,RCB,2016,2021-01-01,6.166667,196.0,43200.0
415,234906,H. Aouar,20,France,80,90,Olympique Lyonnais,23500.0,51.0,Right,1.0,4.0,LM,2016,2023-01-01,5.750000,154.0,49400.0
228,230658,Arthur,21,Brazil,82,90,FC Barcelona,32500.0,125.0,Right,1.0,4.0,LCM,2018,2024-01-01,5.583333,161.0,73100.0
734,231691,A. Lafont,19,France,78,90,Fiorentina,14000.0,12.0,Right,2.0,1.0,GK,2018,2023-01-01,6.333333,181.0,26600.0
1070,237715,P. Cutrone,20,Italy,77,89,Milan,16000.0,62.0,Right,1.0,3.0,RS,2015,2023-01-01,6.000000,172.0,30400.0

## **22. Find the top 10 players aged 30 or above with the highest `Overall` rating.**

In [ ]:
ds[ds['Age'] >= 30].sort_values('Overall', ascending=False).head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
7,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
13,168542,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,Left,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.0
12,182493,D. Godín,32,Uruguay,90,90,Atlético Madrid,44000.0,125.0,Right,3.0,2.0,CB,2010,2019-01-01,6.166667,172.0,90200.0
24,138956,G. Chiellini,33,Italy,89,89,Juventus,27000.0,215.0,Left,4.0,2.0,LCB,2005,2020-01-01,6.166667,187.0,44600.0
22,167495,M. Neuer,32,Germany,89,89,FC Bayern München,38000.0,130.0,Right,5.0,1.0,GK,2011,2021-01-01,6.333333,203.0,62700.0
21,179813,E. Cavani,31,Uruguay,89,89,Paris Saint-Germain,60000.0,200.0,Right,4.0,3.0,LS,2013,2020-01-01,6.083333,170.0,111000.0

## **23. Filter players with `Overall >= 85` and compare their average `Value`, `Wage`, `Age`, and `Potential` with players having `Overall < 85`.**

In [ ]:
ds.groupby(
    ds["Overall"].apply(lambda x: 'Overall >= 85' if x >= 85 else 'Overall < 85')
    )[["Value", "Wage", "Age", "Potential"]].mean()

                      Value        Wage        Age  Potential
Overall
Overall < 85    4170.022815   16.009678  26.912664  74.518352
Overall >= 85  48968.181818  187.663636  28.345455  88.263636

## **24. Create a correlation matrix using Pandas for the numeric columns such as `Age`, `Overall`, `Potential`, `Value`, `Wage`, `International Reputation`, `Skill Moves`, `Height`, `Weight`, and `Release Clause`.**

In [ ]:
nc = [
    "Age",
    "Overall",
    "Potential",
    "Value",
    "Wage",
    "International Reputation",
    "Skill Moves",
    "Height",
    "Weight",
    "Release Clause"
]
ds[nc].corr()

,Age,Overall,Potential,Value,Wage,International Reputation,Skill Moves,Height,Weight,Release Clause
Age,1.000000,0.081850,-0.499361,-0.110492,0.008043,0.238505,-0.185074,0.064958,0.162600,-0.115180
Overall,0.081850,1.000000,0.729534,0.812899,0.702210,0.659997,0.218808,0.036977,0.064389,0.776337
Potential,-0.499361,0.729534,1.000000,0.684919,0.537459,0.401933,0.227436,0.015097,-0.028486,0.663582
Value,-0.110492,0.812899,0.684919,1.000000,0.836054,0.618143,0.259365,-0.007780,0.002317,0.971619
Wage,0.008043,0.702210,0.537459,0.836054,1.000000,0.635053,0.191205,0.017535,0.033755,0.805145
International Reputation,0.238505,0.659997,0.401933,0.618143,0.635053,1.000000,0.151599,0.041408,0.079460,0.582372
Skill Moves,-0.185074,0.218808,0.227436,0.259365,0.191205,0.151599,1.000000,-0.502022,-0.473010,0.240635
Height,0.064958,0.036977,0.015097,-0.007780,0.017535,0.041408,-0.502022,1.000000,0.774863,-0.008341
Weight,0.162600,0.064389,-0.028486,0.002317,0.033755,0.079460,-0.473010,0.774863,1.000000,-0.003643
Release Clause,-0.115180,0.776337,0.663582,0.971619,0.805145,0.582372,0.240635,-0.008341,-0.003643,1.000000

## **25. Calculate the correlation between `Overall` and `Potential`, and also between `Age` and `Potential` using Pandas.**

In [ ]:
overall_corr = ds['Overall'].corr(ds['Potential'])
age_corr = ds['Age'].corr(ds['Potential'])
print(overall_corr)
print(age_corr)

0.7295342123842972
-0.4993609208719726

## **26. Calculate the correlation between `Value` and `Wage`. Then find the 10 highest-valued players and compare their `Value` and `Wage`.**

In [ ]:
cor = ds['Value'].corr(ds['Wage'])
print(cor)
ds.sort_values('Value', ascending=False).head(10)

0.8360543513247832

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
15,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0
16,202126,H. Kane,24,England,89,91,Tottenham Hotspur,83500.0,205.0,Right,3.0,3.0,ST,2010,2024-01-01,6.166667,196.0,160700.0
25,231747,K. Mbappé,19,France,88,95,Paris Saint-Germain,81000.0,100.0,Right,3.0,5.0,RM,2018,2022-01-01,5.833333,161.0,166100.0
7,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
17,194765,A. Griezmann,27,France,89,90,Atlético Madrid,78000.0,145.0,Left,4.0,4.0,CAM,2014,2023-01-01,5.750000,161.0,165800.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

## **27. Group players by `International Reputation` and calculate the count of players plus the average `Overall`, `Value`, and `Wage` for each reputation level.**

In [ ]:
ds[:3]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [ ]:
ds.groupby('International Reputation').agg(
    players = ('Name', 'count'),
    overall_avg = ('Overall', 'mean'),
    value_avg = ('Value', 'mean'),
    wage_avg = ('Wage', 'mean')
)

                          players  overall_avg     value_avg    wage_avg
International Reputation
1.0                          6982    70.789745   3056.567698   11.449871
2.0                          1235    75.808097   8256.286885   32.462348
3.0                           309    81.333333  21653.957655   82.084142
4.0                            51    86.215686  39339.215686  177.156863
5.0                             6    90.833333  73000.000000  310.000000

## **28. Group players by `Skill Moves` and calculate the player count plus the average `Overall`, `Potential`, `Value`, and `Wage` for each skill-move level.**

In [ ]:
ds.groupby('Skill Moves').agg(
    players = ('Name', 'count'),
    overall_avg = ('Overall', 'mean'),
    pot_avg = ('Potential', 'mean'),
    wage_avg = ('Wage', 'mean')
)

             players  overall_avg    pot_avg   wage_avg
Skill Moves
1.0              790    72.144304  74.496203  14.762025
2.0             2475    71.074747  73.390707  14.013737
3.0             4420    71.590498  74.511991  16.539819
4.0              849    76.190813  79.180212  38.817432
5.0               49    80.224490  82.489796  79.285714

## **29. Create a Pandas cross-tabulation showing the number of Left-footed and Right-footed players in each `Position`.**

In [ ]:
pd.crosstab(
    ds['Position'],
    ds['Preferred Foot']
)

Preferred Foot  Left  Right
Position
CAM              153    350
CB               144    536
CDM               57    383
CF                 7     24
CM               100    358
GK                97    693
LAM                9     11
LB               518     53
LCB              163    257
LCM               73    187
LDM               28    131
LF                 2      9
LM               168    375
LS                25    117
LW                49    134
LWB               27      8
RAM                9     10
RB                 2    597
RCB               21    420
RCM               28    216
RDM               15    159
RF                 4      9
RM               153    384
RS                24    115
RW                69    117
RWB                0     31
ST               148    806

## **30. For every `Club`, find the player with the highest `Overall` rating and display the `Club`, `Name`, `Position`, and `Overall`.**

In [ ]:
ds.loc[ds.groupby('Club')['Overall'].idxmax(),
       ['Club', 'Name', 'Position', 'Overall']].sort_values('Club')

                       Club            Name Position  Overall
4587    SSV Jahn Regensburg     M. Grüttner       RS       71
2053  1. FC Heidenheim 1846  M. Schnatterer       LM       75
5084   1. FC Kaiserslautern      L. Spalvis       ST       70
189              1. FC Köln         T. Horn       GK       83
4309        1. FC Magdeburg     R. Brégerie       CB       71
...                     ...             ...      ...      ...
5919         Zagłębie Lubin    M. Dąbrowski      RCB       69
1531        Çaykur Rizespor         A. Umar       RM       76
4344              Örebro SK       N. Besara      CAM       71
6023          Östersunds FK        H. Aiesh       LW       69
5067          Śląsk Wrocław        M. Robak       LS       70

[614 rows x 4 columns]

## **31. For every `Nationality`, find the most valuable player and display the `Nationality`, `Name`, `Club`, `Value`, and `Overall`.**

In [ ]:
ds[:2]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [ ]:
ds.loc[ds.groupby('Nationality')['Value'].idxmax(),['Nationality', 'Name', 'Club', 'Value', 'Overall']].sort_values('Nationality')

KeyError: '[nan] not in index'

## **32. Convert `Contract Valid Until` to a Pandas datetime column, extract the contract expiry year, and find how many players have contracts expiring in each year.**

## **33. Using the extracted contract expiry year, calculate the average `Overall`, `Value`, and `Wage` of players for each contract expiry year.**

In [ ]:
ds.groupby("Contract_Expiry_Year")[["Overall", "Value", "Wage"]].mean().sort_index()

KeyError: 'Contract_Expiry_Year'

## **34. Create a new column called `Years_At_Club` using `2018 - Joined`. Group players by `Years_At_Club` and calculate the average `Overall` and `Wage` to study how club tenure relates to performance and salary.**

## **35. Create a new column called `Release_Value_Ratio` as `Release Clause / Value`. Exclude missing or zero `Value` records, then display the top 10 players with the highest release-clause-to-value ratio.**